(rule
 (targets (dir vendor_install))
 (deps (source_tree vendor)
       scripts/build_vendor_deps.sh)
 (action
  (setenv VENDOR_BUILD_ROOT vendor_build
   (setenv YICES2_FORCE_LOCAL %{env:YICES2_FORCE_LOCAL=0}
    (setenv YICES2_ENABLE_MCSAT %{env:YICES2_ENABLE_MCSAT=1}
     (setenv YICES2_ENABLE_DELEGATES %{env:YICES2_ENABLE_DELEGATES=1}
      (setenv YICES2_WITHOUT_DELEGATES %{env:YICES2_WITHOUT_DELEGATES=}
       (setenv YICES2_SMT2_STATIC %{env:YICES2_SMT2_STATIC=0}
       (run %{project_root}/scripts/build_vendor_deps.sh
            --project-root %{project_root}
            --prefix vendor_install)))))))))

(alias
 (name vendor_deps)
 (deps vendor_install))

(alias
 (name default)
 (deps (alias vendor_deps)))

(rule
 (alias install)
 (deps (alias vendor_deps)
       scripts/install_vendor_deps.sh)
 (action
  (run %{project_root}/scripts/install_vendor_deps.sh
       --from-prefix vendor_install
       --prefix %{env:OPAM_SWITCH_PREFIX=})))
